dofile(factory.modpath.."/items/crafting.lua")
dofile(factory.modpath.."/items/craftitems.lua")
dofile(factory.modpath.."/items/gears.lua")
dofile(factory.modpath.."/items/moving_item.lua")
dofile(factory.modpath.."/items/wires.lua")
dofile(factory.modpath.."/items/storage_tank.lua")